server:
  port: ${SERVER_PORT}
spring:
  # jackson:
  #   serialization:
  #     fail-on-empty-beans: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # jdbc:
        #   lob:
        #     non_contextual_creation: true
logging:
  file:
    path: /